const $ = (q)=>document.querySelector(q);
const today = ()=>new Date().toISOString().slice(0,10);
const money = n=>'Rs. '+Number(n||0).toLocaleString('en-LK',{maximumFractionDigits:2});
const uid = p=>p+'-'+Date.now().toString(36).slice(-5)+'-'+Math.random().toString(36).slice(2,5);
const storeKey='pure-pos-v1';
let state = JSON.parse(localStorage.getItem(storeKey)||'{}');
const defaults={leads:[],quotes:[],customers:[],suppliers:[],purchases:[],invoices:[],expenses:[],bank:[],settings:{theme:'dark'}};
state={...defaults,...state,settings:{...defaults.settings,...(state.settings||{})}};
function save(){localStorage.setItem(storeKey,JSON.stringify(state));}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function setTheme(){document.documentElement.dataset.theme=state.settings.theme==='light'?'light':'dark'}; setTheme();
const pages=[['dashboard','Dashboard','⌁'],['leads','Leads','◎'],['quotes','Quotations','◫'],['customers','Customers','◉'],['invoices','Bills / Invoices','▣'],['suppliers','Suppliers','▤'],['expenses','Expenses','−'],['reports','Reports','◌'],['bank','Bank Upload','⇧']];
let page='dashboard';
function renderNav(){ $('#nav').innerHTML=pages.map(p=>`<button class="navbtn ${page===p[0]?'active':''}" onclick="go('${p[0]}')"><span>${p[2]} ${p[1]}</span><span>›</span></button>`).join(''); }
function go(p){page=p;$('#pageTitle').textContent=pages.find(x=>x[0]===p)[1];renderNav();render();$('#side').classList.remove('open')}
$('#menuBtn').onclick=()=>$('#side').classList.add('open');
$('#themeBtn').onclick=()=>{state.settings.theme=state.settings.theme==='dark'?'light':'dark';save();setTheme()};
$('#exportBtn').onclick=()=>download('pure-pos-backup.json',JSON.stringify(state,null,2));
$('#wipeBtn').onclick=()=>{if(confirm('Reset all local POS data?')){localStorage.removeItem(storeKey);location.reload()}};
$('#seedBtn').onclick=seed;
function download(name, text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click()}
function products(){return {"500ml":{sell:50,bottle:34,label:3},"1000ml":{sell:80,bottle:53.5,label:4.5},"1500ml":{sell:100,bottle:66.5,label:4.5}}}
function metrics(){
 const m=new Date().toISOString().slice(0,7), inv=state.invoices.filter(x=>(x.date||'').startsWith(m)), exp=state.expenses.filter(x=>(x.date||'').startsWith(m));
 const revenue=inv.reduce((s,x)=>s+x.total,0), paid=inv.reduce((s,x)=>s+x.paid,0), costs=inv.reduce((s,x)=>s+x.cost,0), expenses=exp.reduce((s,x)=>s+Number(x.amount||0),0);
 return {revenue,paid,costs,expenses,profit:revenue-costs-expenses,receivable:inv.reduce((s,x)=>s+x.balance,0),avgSupply: inv.length? Math.round(inv.reduce((s,x)=>s+x.qty,0)/inv.length):0};
}
function render(){({dashboard,leads,quotes,customers,invoices,suppliers,expenses,reports,bank}[page])()}
function card(title, inner){return `<div class="card"><h2>${title}</h2>${inner}</div>`}
function dashboard(){const m=metrics();$('#content').innerHTML=`
 <div class="grid">
  ${[['Revenue',money(m.revenue)],['Profit / Loss',money(m.profit)],['Cash Collected',money(m.paid)],['Receivables',money(m.receivable)],['Monthly Avg Supply',m.avgSupply+' bottles'],['Leads',state.leads.length],['Customers',state.customers.length],['Open Quotes',state.quotes.filter(q=>q.status!=='Closed').length]].map(x=>`<div class="card metric"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
 </div><div class="split" style="margin-top:12px">
 ${card('Quick Actions',`<div class="actions"><button class="primary" onclick="go('leads')">Add Lead</button><button class="primary" onclick="go('quotes')">Create Quotation</button><button class="primary" onclick="go('invoices')">Generate Bill</button></div><p class="sub">Mobile-first staff app. Add to iPhone Home Screen after hosting on GitHub Pages.</p>`)}
 ${card('Business Pulse',`<div class="kpi-line"><span>Cost of Goods</span><b>${money(m.costs)}</b></div><div class="kpi-line"><span>Expenses</span><b>${money(m.expenses)}</b></div><div class="kpi-line"><span>Net result</span><b>${money(m.profit)}</b></div>`)}
 </div>`}
function leads(){ $('#content').innerHTML=`<div class="split">${card('Add Lead',leadForm())}${card('Lead List',table(state.leads,['date','business','contact','phone','status'],l=>`<button class="mini" onclick="quoteFromLead('${l.id}')">Quote</button> <button class="mini danger" onclick="del('leads','${l.id}')">Delete</button>`))}</div>`;}
function leadForm(){return `<form class="form" onsubmit="addLead(event)"><label>Date<input type="date" name="date" value="${today()}"></label><label>Business / Brand<input name="business" required placeholder="Cafe / Hotel / Event"></label><label>Contact Person<input name="contact" required></label><label>Phone<input name="phone" required></label><label>Address<textarea name="address"></textarea></label><label>Status<select name="status"><option>New</option><option>Negotiating</option><option>Won</option><option>Lost</option></select></label><button class="primary">Save Lead</button></form>`}
function addLead(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target));state.leads.unshift({id:uid('L'),...o});save();toast('Lead saved');leads()}
function quoteFromLead(id){go('quotes'); setTimeout(()=>{let s=$('#quoteLead'); if(s){s.value=id; fillLead();}},0)}
function quotes(){ $('#content').innerHTML=`<div class="split">${card('Create Quotation',quoteForm())}${card('Quotations',table(state.quotes,['date','customer','product','qty','total','status'],q=>`<button class="mini" onclick="pdfQuote('${q.id}')">PDF</button> <button class="mini" onclick="closeQuote('${q.id}')">Close Sale</button> <button class="mini danger" onclick="del('quotes','${q.id}')">Delete</button>`))}</div>`;}
function quoteForm(){let opts=state.leads.map(l=>`<option value="${l.id}">${l.business} - ${l.contact}</option>`).join('');return `<form class="form" onsubmit="addQuote(event)"><label>Lead<select id="quoteLead" name="leadId" onchange="fillLead()"><option value="">Manual customer</option>${opts}</select></label><label>Customer / Brand<input id="qCustomer" name="customer" required></label><div class="row"><label>Product<select name="product" id="qProduct" onchange="quoteCalc()">${Object.keys(products()).map(p=>`<option>${p}</option>`)}</select></label><label>Quantity<input name="qty" id="qQty" type="number" value="3000" oninput="quoteCalc()"></label></div><div class="row"><label>Selling price / bottle<input name="unit" id="qUnit" type="number" step=".01" value="50" oninput="quoteCalc()"></label><label>Cap printing / bottle<input name="cap" type="number" step=".01" value="0" oninput="quoteCalc()"></label></div><div class="row"><label>Design cost<input name="design" type="number" step=".01" value="0" oninput="quoteCalc()"></label><label>Advance / label cost<input name="advance" id="qAdvance" type="number" step=".01" value="9000"></label></div><label>Notes<textarea name="notes" placeholder="Quotation valid until full label stock completed."></textarea></label><div class="pill" id="qTotal">Total: Rs. 150,000</div><button class="primary">Save Quotation</button></form>`}
function fillLead(){let l=state.leads.find(x=>x.id===$('#quoteLead').value); if(l) $('#qCustomer').value=l.business;}
function quoteCalc(){let p=$('#qProduct').value, d=products()[p]; $('#qUnit').value=$('#qUnit').value||d.sell; let f=$('#qProduct').closest('form'), o=Object.fromEntries(new FormData(f)); let total=Number(o.qty||0)*(Number(o.unit||0)+Number(o.cap||0))+Number(o.design||0); $('#qTotal').textContent='Total: '+money(total);}
function addQuote(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.qty=+o.qty;o.unit=+o.unit;o.cap=+o.cap;o.design=+o.design;o.advance=+o.advance;o.total=o.qty*(o.unit+o.cap)+o.design;o.date=today();o.status='Open';state.quotes.unshift({id:uid('Q'),...o});save();toast('Quotation saved');quotes()}
function closeQuote(id){let q=state.quotes.find(x=>x.id===id); if(!q)return; let lead=state.leads.find(l=>l.id===q.leadId)||{}; state.customers.unshift({id:uid('C'),date:today(),brand:q.customer,contact:lead.contact||'',phone:lead.phone||'',address:lead.address||'',advancePaid:q.advance,labelStock:{[q.product]:q.qty},notes:'Converted from quotation '+q.id}); q.status='Closed'; save();toast('Customer added');go('customers')}
function customers(){ $('#content').innerHTML=`<div class="split">${card('Add Customer',customerForm())}${card('Official Customers',table(state.customers,['date','brand','contact','phone','advancePaid'],c=>`<button class="mini" onclick="viewCustomer('${c.id}')">View</button> <button class="mini danger" onclick="del('customers','${c.id}')">Delete</button>`))}</div>`;}
function customerForm(){return `<form class="form" onsubmit="addCustomer(event)"><label>Brand / Customer<input name="brand" required></label><label>Contact Person<input name="contact"></label><label>Phone<input name="phone"></label><label>Address<textarea name="address"></textarea></label><label>Advance Paid<input name="advancePaid" type="number" value="0"></label><button class="primary">Add Customer</button></form>`}
function addCustomer(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target));state.customers.unshift({id:uid('C'),date:today(),labelStock:{},...o,advancePaid:+o.advancePaid});save();customers();toast('Customer added')}
function viewCustomer(id){let c=state.customers.find(x=>x.id===id);alert(`${c.brand}\nContact: ${c.contact}\nPhone: ${c.phone}\nAdvance: ${money(c.advancePaid)}\nLabel stock: ${JSON.stringify(c.labelStock)}`)}
function invoices(){ $('#content').innerHTML=`<div class="split">${card('Generate Customer Bill',invoiceForm())}${card('Invoice List',table(state.invoices,['date','customer','product','qty','total','balance'],i=>`<button class="mini" onclick="pdfInvoice('${i.id}')">PDF</button> <button class="mini danger" onclick="del('invoices','${i.id}')">Delete</button>`))}</div>`;}
function invoiceForm(){let opts=state.customers.map(c=>`<option value="${c.id}">${c.brand}</option>`).join('');return `<form class="form" onsubmit="addInvoice(event)"><label>Customer<select name="customerId" required>${opts}</select></label><div class="row"><label>Product<select name="product">${Object.keys(products()).map(p=>`<option>${p}</option>`)}</select></label><label>Qty supplied<input name="qty" type="number" required></label></div><div class="row"><label>Selling price / bottle<input name="unit" type="number" step=".01" required value="50"></label><label>Paid now<input name="paid" type="number" step=".01" value="0"></label></div><label>Payment type<select name="payType"><option>Cash</option><option>Bank Transfer</option><option>Pay Later</option></select></label><button class="primary">Save & Generate Bill</button></form>`}
function addInvoice(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target)), c=state.customers.find(x=>x.id===o.customerId), p=products()[o.product];let qty=+o.qty,total=qty*(+o.unit), paid=+o.paid, cost=qty*(p.bottle+p.label);c.labelStock[o.product]=Math.max(0,Number(c.labelStock[o.product]||0)-qty);let inv={id:uid('INV'),date:today(),customer:c.brand,customerId:c.id,product:o.product,qty,unit:+o.unit,total,paid,balance:total-paid,cost,payType:o.payType};state.invoices.unshift(inv);save();toast('Invoice saved');pdfInvoice(inv.id);invoices()}
function suppliers(){ $('#content').innerHTML=`<div class="split">${card('Add Supplier Purchase',purchaseForm())}${card('Supplier Bills / Purchases',table(state.purchases,['date','supplier','item','qty','unitCost','total'],p=>`<button class="mini danger" onclick="del('purchases','${p.id}')">Delete</button>`))}</div>`;}
function purchaseForm(){return `<form class="form" onsubmit="addPurchase(event)"><label>Supplier<select name="supplier"><option>Sopanro Beverages</option><option>Artline Printing</option><option>Other</option></select></label><label>Item<input name="item" placeholder="500ml bottle / 500ml label"></label><div class="row"><label>Qty<input name="qty" type="number"></label><label>Unit Cost<input name="unitCost" type="number" step=".01"></label></div><label>Bill note<textarea name="note"></textarea></label><button class="primary">Save Purchase</button></form>`}
function addPurchase(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.qty=+o.qty;o.unitCost=+o.unitCost;o.total=o.qty*o.unitCost;o.date=today();state.purchases.unshift({id:uid('P'),...o});save();suppliers();toast('Purchase saved')}
function expenses(){ $('#content').innerHTML=`<div class="split">${card('Add Expense',expenseForm())}${card('Expenses',table(state.expenses,['date','category','amount','note'],x=>`<button class="mini danger" onclick="del('expenses','${x.id}')">Delete</button>`))}</div>`;}
function expenseForm(){return `<form class="form" onsubmit="addExpense(event)"><label>Date<input type="date" name="date" value="${today()}"></label><label>Category<select name="category"><option>Salaries</option><option>Telephone Bills</option><option>Electricity</option><option>Water Bills</option><option>Delivery</option><option>Other</option></select></label><label>Amount<input name="amount" type="number" step=".01" required></label><label>Note<textarea name="note"></textarea></label><button class="primary">Save Expense</button></form>`}
function addExpense(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target));state.expenses.unshift({id:uid('E'),...o,amount:+o.amount});save();expenses();toast('Expense saved')}
function reports(){let m=metrics();$('#content').innerHTML=`<div class="split">${card('Monthly Profit / Loss Statement',`<div class="kpi-line"><span>Sales Revenue</span><b>${money(m.revenue)}</b></div><div class="kpi-line"><span>COGS</span><b>${money(m.costs)}</b></div><div class="kpi-line"><span>Operating Expenses</span><b>${money(m.expenses)}</b></div><div class="kpi-line"><span>Net Profit / Loss</span><b>${money(m.profit)}</b></div><button class="primary" onclick="pdfReport()">Export Month PDF</button>`)}${card('Customer Order Behavior',behavior())}</div>`}
function behavior(){let rows=state.customers.map(c=>{let inv=state.invoices.filter(i=>i.customerId===c.id);return `<tr><td>${c.brand}</td><td>${inv.length}</td><td>${inv.reduce((s,i)=>s+i.qty,0)}</td><td>${money(inv.reduce((s,i)=>s+i.total,0))}</td></tr>`}).join('');return `<div class="scroll"><table><tr><th>Customer</th><th>Orders</th><th>Bottles</th><th>Value</th></tr>${rows}</table></div>`}
function bank(){ $('#content').innerHTML=card('Bank Statement Upload',`<p class="sub">Upload a CSV bank statement. This MVP stores a preview locally. Later we can match deposits with invoice payments.</p><input type="file" accept=".csv" onchange="bankCsv(event)"><div class="scroll"><table><tr><th>Date</th><th>Description</th><th>Amount</th></tr>${state.bank.slice(0,30).map(r=>`<tr><td>${r[0]||''}</td><td>${r[1]||''}</td><td>${r[2]||''}</td></tr>`).join('')}</table></div>`)}
function bankCsv(e){let f=e.target.files[0]; if(!f)return;let r=new FileReader();r.onload=()=>{state.bank=r.result.split(/\n/).map(x=>x.split(',')).filter(x=>x.length>1);save();bank();toast('Bank CSV uploaded')};r.readAsText(f)}
function table(arr, cols, actions){if(!arr.length)return '<div class="empty">No records yet. The ledger is still a quiet pond.</div>';return `<div class="scroll"><table><tr>${cols.map(c=>`<th>${c}</th>`).join('')}<th>Action</th></tr>${arr.map(o=>`<tr>${cols.map(c=>`<td>${c==='total'||c==='balance'||c==='advancePaid'||c==='unitCost'||c==='amount'?money(o[c]):(o[c]??'')}</td>`).join('')}<td class="actions">${actions(o)}</td></tr>`).join('')}</table></div>`}
function del(k,id){state[k]=state[k].filter(x=>x.id!==id);save();render();toast('Deleted')}
function docBase(title){const {jsPDF}=window.jspdf;let doc=new jsPDF();doc.setFillColor(5,5,5);doc.rect(0,0,210,35,'F');doc.addImage('assets/logo.png','PNG',55,8,100,18);doc.setFontSize(18);doc.text(title,14,50);return doc}
function pdfQuote(id){let q=state.quotes.find(x=>x.id===id);let doc=docBase('Quotation');doc.setFontSize(11);let y=62;[['Date',q.date],['Customer',q.customer],['Product',q.product],['Quantity',q.qty],['Unit Price',money(q.unit)],['Cap Printing',money(q.cap)],['Design Cost',money(q.design)],['Advance / Label Cost',money(q.advance)],['Total',money(q.total)],['Status',q.status]].forEach(r=>{doc.text(`${r[0]}: ${r[1]}`,14,y);y+=8});doc.text('Pure Custom Creation - Your Trusted Branding Partner',14,280);doc.save(`Quotation-${q.customer}.pdf`)}
function pdfInvoice(id){let i=state.invoices.find(x=>x.id===id);let doc=docBase('Customer Bill / Invoice');doc.setFontSize(11);let y=62;[['Invoice ID',i.id],['Date',i.date],['Customer',i.customer],['Product',i.product],['Quantity supplied',i.qty],['Unit price',money(i.unit)],['Total',money(i.total)],['Paid now',money(i.paid)],['Balance',money(i.balance)],['Payment',i.payType]].forEach(r=>{doc.text(`${r[0]}: ${r[1]}`,14,y);y+=8});doc.text('Thank you for choosing Pure Custom Creation.',14,270);doc.save(`Bill-${i.customer}-${i.date}.pdf`)}
function pdfReport(){let m=metrics(),doc=docBase('Monthly Profit / Loss Statement');doc.setFontSize(11);let y=65;[['Revenue',m.revenue],['COGS',m.costs],['Expenses',m.expenses],['Net Profit / Loss',m.profit],['Receivables',m.receivable]].forEach(r=>{doc.text(`${r[0]}: ${money(r[1])}`,14,y);y+=10});doc.save('Pure-Monthly-PL.pdf')}
function seed(){state.leads=[{id:'L-demo',date:today(),business:'Demo Cafe',contact:'Nimal',phone:'0770000000',address:'Kandy',status:'Negotiating'}];state.customers=[{id:'C-demo',date:today(),brand:'Lake View Hotel',contact:'Kasun',phone:'0711111111',address:'Kandy',advancePaid:9000,labelStock:{'500ml':3000}}];state.expenses=[{id:'E-demo',date:today(),category:'Telephone Bills',amount:1500,note:'Monthly'}];save();toast('Demo data loaded');render()}
renderNav();render();
